# Generated by Django 4.2.14 on 2024-07-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_otpvalidator_rename_phone_number_user_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
