# Generated by Django 4.2.14 on 2024-07-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chit_fund', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='groups',
        ),
        migrations.AlterModelTable(
            name='groupscheme',
            table='group_scheme',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
        migrations.AlterModelTable(
            name='scheme',
            table='schemes',
        ),
        migrations.AlterModelTable(
            name='withdrawal',
            table='withdrawals',
        ),
    ]
