# Generated by Django 4.2.14 on 2024-07-13 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chit_fund', '0002_alter_group_table_alter_groupscheme_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='new_installment_amount',
        ),
        migrations.AddField(
            model_name='group',
            name='group_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='current_month',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AlterField(
            model_name='groupscheme',
            name='current_month',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='groupscheme',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='duration_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='groupscheme',
            table='group_schemes',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chit_fund_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
