# Generated by Django 4.2.14 on 2024-08-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit_fund', '0003_remove_withdrawal_new_installment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='groupscheme',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
